### PR TITLE
EMPDLess node attach

### PR DESCRIPTION
**Pull request by oltarasenko**
Contains node_attach_template script which allows to attach to
EPMDLess nodes

### CODE REVIEW

**Comment by tsloughter** [comment]
I'm not really a fan of this solution. For one thing, escript shell is buggy, which is one reason I have `rebar3 local install` for installing rebar3 unpacked to make `rebar3 shell` less annoying by not running through an escript.

Maybe not as much of a concern when it comes to a remote shell but it also requires another script to be duplicated to repos and copied into the release like the old days before relx :).

**Comment by oltarasenko** [comment]
:( Yeah, I understand your point. Indeed, we had to copy this script into our releases. 

In issue #2 you have mentioned the idea of having an extra fallback for a port_please? Could you send the  PR please if possible?

**Comment by tsloughter** [comment]
Yup, will do tomorrow.

**Comment by tsloughter** [comment]
Still have this on my todo. I had to rethink it a little bit to work with the relx scripts properly. I think it'll work fine by using an os var, should have it verified and open a PR in the morning.

**Comment by oltarasenko** [comment]
Yeah, it would be nice to see how it could work (as for now I don't have a clear idea, from my point of view we somehow need to start empdless from -remsh, and to register a node there...).

**Pull request closed without merging**
