### PR TITLE
Small propose of few changes

### PR DESCRIPTION
**Pull request by vkatsuba**
### What was implemented:
- Moved header file into **include** directory
- Updated **rebar.config** for build release
- Added **vm.args** with base erl flags
- Added few **Common Tests**
- Added **Makefile**

### How To:
- Build and run:
```sh
$ make
```
- Run common tests:
```sh
$ make ct
```
- Clean project
```sh
$ make clean
```
- Example:
```erlang
(epmdless@pc)1> epmdless_client:add_node('app1@host.local', 17012).
ok
(epmdless@pc)2> epmdless_client:list_nodes().
[{'app1@host.local',{"host.local",17012}}]
```

### CODE REVIEW

**Comment by tsloughter** [comment]
The header file should stay in `src` since it is not meant for public consumption of another application using epmdless as a dependency.

And the common test test doesn't really work, it requires epmd to be running as far as I could tell. I instead adding a test that runs through a script that builds an example. Happy to have a CT suite as well but not sure how it could be done yet.

**Comment by vkatsuba** [comment]
Hi @tsloughter, thanks for updates. I can close this PR or if you can, please provide to me some approach about CT and I will try implemented it.

**Comment by tsloughter** [comment]
Are you using epmdless in production by chance? I'm looking to find those who are.

Sorry, I don't have an idea yet on how the common test suite could be done. So I guess close it, will try to figure something out eventually -- aside from the script testing.

**Comment by vkatsuba** [comment]
No, I'm not using the epmdless in production. I'm just a kind samaritan who is interested in contribution of interesting open source projects/ideas. Ok, I will close this PR, if you will have any ideas how I can be helpful you always can ping me by email v.katsuba.dev@gmail.com.

Regards,
--V

**Pull request closed without merging**
